#!/bin/sh

usage() {
    echo "This is default download recipe for leech"
}

if [ -z "$LEECH_DOWNLOADS_DIR" ]; then
    usage
    exit 1
fi

cd "$LEECH_DOWNLOADS_DIR" && exec \
	curl -s -f \
	--connect-timeout "$LEECH_TIMEOUT" --max-time "$LEECH_TIMEOUT" \
	-C - \
	-o "$LEECH_URL_MD5.torrent" "$LEECH_URL"
